name: dockerloginDEVQA

on:
  push:
    branches: [ "main" ]
  pull_requests:
    branches: [ "main" ]
jobs:
  LogintodockerhubDEV:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v3
    - name: docker/login
      uses: docker/login-action@v2.1.0
      with: 
        username: $
        password: $
    - name: Docker Pull
      run: docker pull hello-world
    - name: Docker Tag
      run: docker tag hello-world Nibedita84/Hello_world
    - name: Docker Push
      run: docker push Nibedita84/Hello_world
  LogintodockerhubQA:
    runs-on: ubuntu-latest
    environment: QA
    steps:
    - uses: actions/checkout@v3
    - name: docker/login
      uses: docker/login-action@v2.1.0
      with: 
        username: $
        password: $

  
