name : dockerloginDEVQA

  on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
    workflow_dispatch:
  jobs:
    LogintodockerhubDEV:
      runs-on: ubuntu-latest
      environment: dev_nd
      steps:
      - users: actions/checkout@v3
      - name: docker login
        uses: docker/login-action@v2.1.0
        with:
          registry: registry-1.docker.io
          username: ${{secrets.DOCKERHUBUSERNAME}}
          password: ${{secrets.DOCKERHUBPASSWORD}}
      LogintodockerhubQA:
        runs-on: ubuntu-latest
      environment: qa_nd
      steps:
      - users: actions/checkout@v3
      - name: docker login
        uses: docker/login-action@v2.1.0
        with:
          registry: registry-1.docker.io
          username: ${{secrets.DOCKERHUBUSERNAME}}
          password: ${{secrets.DOCKERHUBPASSWORD}} 
